### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by aliramazanmert**

### CODE REVIEW

**Comment by afgedemenli** [comment]
Irem's right. You can find another solution which does not involve the API key, or maybe just leave that place parametric like <API_KEY>.

**Comment by aliramazanmert** [comment]
You guys are totally right.This was kinda like a prototype for the moment but since now I found the way to actually open the audio file and play the converted speech instead of giving url as an output now the app will give the audio file itself and play it after I update my codes and make another request of course.

**Comment by aliramazanmert** [comment]
Also I asked Halit yesterday morning to add my secret.json file.Tests will work fine after he adds it.

**Comment by aliramazanmert** [comment]
Unfortunately I couldn't find a proper way to test the outcome audio file in tests.py , so tests just test the status and the content type of the returning files which actually should be enough since if the program works that's enough to say it returns the corresponding audio file for the given text.

**Comment by corupta** [comment]
> Also I asked Halit yesterday morning to add my secret.json file.Tests will work fine after he adds it.

Added TS_API_KEY to travis and production server, restarted travis tests, it successfully read the secret, but it seems there's a syntax error created by your direct commit to master, [8d1f95b8](https://github.com/bounswe/bounswe2019group9/commit/8d1f95b84f52ca9253da76648c65a98a55814553)

so, please add the missing comma in `practice-app/home/views.py` at `line 33` as soon as possible and do not commit directly to master, later. (We cannot merge any pull requests before fixing it otherwise the server would be down, hopefully travis runs the tests before deploying to server, so it did not deploy since it failed the test for that commit, although the commit was sent to master.)

**Pull request merged**
