### PR TITLE
Music suggester

### PR DESCRIPTION
**Pull request by emirhanyasin**
By this API, we are adding the functionality of adding, deleting and seeing song suggestions for language learners

### CODE REVIEW

**Comment by corupta** [comment]
please remove virtenv from git using `git rm -r --cached virtenv`
and add `virtenv` to .gitignore

**Comment by corupta** [comment]
Follow directions [here](https://github.com/bounswe/bounswe2019group9/blob/master/practice-app/README.md)

Only add music folder (app folder) not the whole DJANGO project then make a new commit

**Comment by corupta** [comment]
We merged Burhan's code, please resolve conflicts.

**Comment by corupta** [comment]
Also, please add your documentation

**Comment by emirhanyasin** [comment]
#109 done

**Comment by corupta** [comment]
Nice work

**Pull request merged**
